// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpfUITsfVUt5ElNBBGIlnmGTFFkWh3Y4k',
    appId: '1:804551584729:web:f5ac8d2ad851defac8c7c8',
    messagingSenderId: '804551584729',
    projectId: 'flutter-49b29',
    authDomain: 'flutter-49b29.firebaseapp.com',
    storageBucket: 'flutter-49b29.firebasestorage.app',
    measurementId: 'G-BRSM7HKXP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ51L2xbkXvwTLKyY-c7IPU3Wf--s2cLM',
    appId: '1:804551584729:android:74024bedc876076fc8c7c8',
    messagingSenderId: '804551584729',
    projectId: 'flutter-49b29',
    storageBucket: 'flutter-49b29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VoFWpB8D2oXPAuO1hR1AiF_bM4UOhb8',
    appId: '1:804551584729:ios:7b554386cf7337bdc8c7c8',
    messagingSenderId: '804551584729',
    projectId: 'flutter-49b29',
    storageBucket: 'flutter-49b29.firebasestorage.app',
    iosBundleId: 'com.example.untitled11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-VoFWpB8D2oXPAuO1hR1AiF_bM4UOhb8',
    appId: '1:804551584729:ios:7b554386cf7337bdc8c7c8',
    messagingSenderId: '804551584729',
    projectId: 'flutter-49b29',
    storageBucket: 'flutter-49b29.firebasestorage.app',
    iosBundleId: 'com.example.untitled11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpfUITsfVUt5ElNBBGIlnmGTFFkWh3Y4k',
    appId: '1:804551584729:web:822d8a629df7e25fc8c7c8',
    messagingSenderId: '804551584729',
    projectId: 'flutter-49b29',
    authDomain: 'flutter-49b29.firebaseapp.com',
    storageBucket: 'flutter-49b29.firebasestorage.app',
    measurementId: 'G-4X41G271DV',
  );
}
